language: cpp

# $PROJ_BUILD_DIR must not be co-located with the source directory!
# env:
# global:  # this is useful for future caching, see VXL/.travis.yml
#     - PROJ_SOURCE_DIR=${TRAVIS_BUILD_DIR} # ${HOME}/build/<USER>/<REPO>
#     - PROJ_BUILD_DIR=${HOME}/proj/build
#     - PROJ_INSTALL_DIR=${HOME}/proj/install
      
os:
- linux
- osx
      
compiler:
- gcc  # default 5.4 as of Sept 2019
- clang

jobs:
include:
  - os: linux
    dist: trusty
  - os: osx
    osx_image: xcode11


# additional setup
install:

  # install specific cmake version (minimum vxl requirement)
#   - |
#     if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
#       CMAKE_URL="http://www.cmake.org/files/v3.10/cmake-3.10.2-Linux-x86_64.tar.gz"
#       mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
#       export PATH=${DEPS_DIR}/cmake/bin:${PATH}
#     fi    

# before_script:
  # create build & install directories if they do not exist
#   - mkdir -p ${PROJ_BUILD_DIR} ${PROJ_INSTALL_DIR}
  
# main script
script:
  - cmake --version
  - ${CC} --version
  - cmake .
  - make
  - make install
